### PR TITLE
Chore/move all message to appmessages

### PR DESCRIPTION
**Pull request by justinriggio**
@jacksenechal @auggernaut @harlantwood ready for a review on "Move all message to AppMessages" chore
98% all messages move to the JSON file, might be a few that I didn't see.

*I did it in a branch because it touches a lot of files.

### CODE REVIEW

**Comment by jacksenechal** [comment]
There are a number of messages that can still be pulled into AppMessages. I dug into it with grep, looking for strings. Here's a pretty exhaustive list:

```
src/app/views/we/InsightsView.coffee:118:      content: insight.friend.firstName + " " + insight.friend.lastName
src/app/views/controls/AnswerImageOverlayView.coffee:70:      @text.setContent "source: <a target='_blank' href='#{source}'>#{domain}</a>", true
src/app/views/controls/ActivityItemView.coffee:74:    @titleSurface.setContent "<span class='activity__item__fullname'>Augustin Bralley</span> answered 4 cards about himself.", true
src/app/views/controls/ActivityItemView.coffee:82:      content: "He was in a naughty mood."
src/app/views/controls/ActivityItemView.coffee:117:      @titleSurface.setContent "<span id='activity__item__fullname'>#{EscapeText.forBrowser data.userName}</span> answered #{data.cards.length} cards about #{if data.sex is 'male' then 'himself' else 'herself'}.", true
src/app/views/controls/ActivityItemView.coffee:119:        @detailsSurface.setContent "#{if data.sex is 'male' then 'He' else 'She'} was in a #{data.mood} mood."
src/app/views/controls/ActivityItemView.coffee:127:      @titleSurface.setContent "<span id='activity__item__fullname'>#{EscapeText.forBrowser data.userName}</span> created a card:", true
src/app/views/controls/ActivityItemView.coffee:146:        @titleSurface.setContent "<span id='activity__item__fullname'>#{EscapeText.forBrowser data.userName}</span> pegged you in #{data.tries} #{if data.tries > 1 then 'tries' else 'try'}.", true
src/app/views/controls/ActivityItemView.coffee:148:        @titleSurface.setContent "<span id='activity__item__fullname'>#{EscapeText.forBrowser data.userName}</span> pegged #{EscapeText.forBrowser data.friendName} in #{data.tries} #{if data.tries > 1 then 'tries' else 'try'}.", true
src/app/views/controls/ActivityItemView.coffee:156:      @titleSurface.setContent "<span id='activity__item__fullname'>#{EscapeText.forBrowser data.userName}</span> favorited a card:", true
src/app/views/controls/ActivityItemView.coffee:158:        @detailsSurface.setContent "So did #{data.favorites} other people."
src/app/views/controls/StatsCardView.coffee:150:    @infoText.setContent "#{data.favorites} favorite#{if data.favorites is 1 then '' else 's'} &nbsp; #{if data.total? then data.total else 0} pegg#{if data.total is 1 then '' else 's'}", true
src/app/views/controls/StatsCardView.coffee:174:          @answerHeader.setContent answerHeaderText + " (#{Math.round fraction * 100}%)"
src/app/views/play/NewCardView.coffee:84:      categorySurface.setContent "<span class='category-name'>#{EscapeText.forBrowser category.get 'name'}</span>", true
src/app/views/SignupView.coffee:123:    @signupInput.setValue "Email..."
src/app/views/controls/ActivityItemView.coffee:135:        title = "<span id='activity__item__fullname'>#{EscapeText.forBrowser data.userName}</span> commented on your card:"
src/app/views/controls/ActivityItemView.coffee:137:        title = "<span id='activity__item__fullname'>#{EscapeText.forBrowser data.userName}</span> commented on #{if data.sex is 'male' then 'his' else 'her'} card:"
src/app/views/play/CardView.coffee:517:      name: "How well do YOU know me?"
src/app/views/play/CardView.coffee:519:      caption: "Pegg your friends and see who knows you best!"
src/app/stores/PlayStore.coffee:132:      @_title = "This is a bogus card, bungwallet."
src/app/stores/PlayStore.coffee:134:      @_title = "Pegg #{card.peggee.firstName}!"
src/app/stores/PlayStore.coffee:137:      @_title = "Pegg yourself!"
src/app/stores/PlayStore.coffee:342:      when 'win' then return "Good job!"
src/app/stores/PlayStore.coffee:343:      when 'fail' then return "Boo."
src/app/stores/helpers/Card.coffee:62:    @question = "Ruh roh!<br/><br/>Either this card doesn't exist, or you don't have access to it."
```

**Comment by jacksenechal** [comment]
There is also a subtlety of the naming convention for message keys here. The double underscore is meant for scoping, delineating nested items, etc. Camelcase should be used for any one item, to keep consistency with the naming of the item in code.

For instance:

- `signup__input__placeholder` - this is well formatted, because each separate chunk is a thing. `placeholder` belongs to `input` belongs to `signup`.
- `signup__subscribe__button` - should probably be `signup__subscribeButton`

This is a reduction of the Block-Element-Modifier naming scheme we use for CSS. See https://github.com/PeggApp/pegg#style-guides.

**Comment by justinriggio** [comment]
@jacksenechal @auggernaut 
src/app/views/controls/AnswerImageOverlayView.coffee:70: 
This is a string that builds out a link. I though this task was for "hardcoded messages"?

**Comment by jacksenechal** [comment]
Well there's one word of text in there that's displayed to the user: "source" :) I'm thinking of this task as a preparation for internationalization. If we go ahead and move all text that's displayed to the user into AppMessages it'll be as easy as handing that file off to a translator. So for most of the lines I listed you'd want to make liberal use of the second getText arg.

**Comment by justinriggio** [comment]
Yes your right, but I think I found one that doesn't need to be in the AppMessages:
src/app/views/play/NewCardView.coffee:84:

**Comment by jacksenechal** [comment]
Ah yeah, right you are. That text is coming from the DB.

**Comment by justinriggio** [comment]
@jacksenechal I added the missing text from the files you had found, and fixed the naming of some properties. I think she's ready.

**Comment by justinriggio** [comment]
@jacksenechal Looks like we passed the tests.

**Comment by jacksenechal** [comment]
Awesome, I'll merge it in

**Pull request merged**
